const {test,expect}=require('@playwright/test');

test('sparse exploration fills its row and unavailable bosses expose preparation without extra clicks',async({page},info)=>{
    await page.goto('/tests/fixtures/world-tree-journey/index.html?review=regions');
    await expect(page.locator('#status')).toContainText('실제 전투');
    await page.locator('#legal-build').click();
    await expect(page.locator('#status')).toContainText('T14');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    await page.locator('#atlas').click();
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    const atlas=frame.locator('#ui-exploration-atlas');
    const layout=await atlas.locator('.atlas-destinations').evaluateAll(sections=>sections.map(section=>{
        const card=section.querySelector('.atlas-destination').getBoundingClientRect();
        const bounds=section.getBoundingClientRect();
        return {left:bounds.left,top:bounds.top,width:bounds.width,cardWidth:card.width};
    }));
    expect(layout).toHaveLength(2);
    layout.forEach(section=>expect(Math.abs(section.width-section.cardWidth)).toBeLessThan(2));
    if(info.project.name==='desktop-chromium') {
        expect(Math.abs(layout[0].top-layout[1].top)).toBeLessThan(2);
        expect(layout[1].left).toBeGreaterThan(layout[0].left+layout[0].width);
    } else expect(layout[1].top).toBeGreaterThan(layout[0].top);
    await atlas.screenshot({path:info.outputPath('sparse-destinations.png')});
    await atlas.locator('[data-atlas-route="map-explore-root-boss"]').click();
    const list=frame.locator('#ui-season-boss-list');
    const group=list.locator('[data-map-zone-group="rootBosses"]');
    const header=group.locator('.map-zone-group-header');
    await expect(header).toHaveAttribute('aria-expanded','true');
    await expect(group.locator('.encounter-card').first()).toBeVisible();
    await expect(group.locator('.encounter-footer').first()).toContainText(/열쇠|필요|층/);
    await header.click();
    await expect(header).toHaveAttribute('aria-expanded','false');
    await expect(header).toBeFocused();
    await child.evaluate(()=>updateStaticUI());
    await expect(header).toHaveAttribute('aria-expanded','false');
    await header.click();
    await expect(header).toHaveAttribute('aria-expanded','true');
    await expect(header).toBeFocused();
    await list.screenshot({path:info.outputPath('boss-preparation.png')});
});

test('ready expedition disclosure retains focus and open state during combat refresh',async({page})=>{
    await page.goto('/tests/fixtures/world-tree-journey/index.html');
    await expect(page.locator('#status')).toContainText('실제 전투');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    await child.evaluate(()=>{game.currencies.hiveKey=1;updateStaticUI();});
    await page.locator('#atlas').click();
    await frame.getByRole('button',{name:'나무',exact:true}).click();
    const disclosure=frame.locator('#map-ready-destinations details');
    await disclosure.locator('summary').click();
    await expect(disclosure).toHaveAttribute('open');
    await disclosure.locator('summary').focus();
    // A new ready destination changes the actual markup while the player is using the disclosure.
    await child.evaluate(()=>{game.starWedge.skyRiftReady=true;updateStaticUI();});
    await expect(disclosure).toHaveAttribute('open');
    await expect(disclosure.locator('summary')).toBeFocused();
    await expect(disclosure).toContainText('운석 낙하');
    await disclosure.locator('summary').click();
    await child.evaluate(()=>updateStaticUI());
    await expect(disclosure).not.toHaveAttribute('open');
    await expect(disclosure.locator('summary')).toBeFocused();
});

test('new trial cue follows unfinished eligible trials and travel locks',async({page},info)=>{
    await page.goto('/tests/fixtures/world-tree-journey/index.html?review=regions');
    await expect(page.locator('#status')).toContainText('실제 전투');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    const card=frame.locator('[data-atlas-route="map-explore-trials"]');
    await child.evaluate(()=>{
        game.level=90;game.currentZoneId=0;game.maxZoneId=3;game.combatHalted=true;
        game.completedTrials=['trial_1'];game.unlockedTrials=[];updateStaticUI();
    });
    await expect(card).not.toHaveClass(/has-new-challenge/);
    await child.evaluate(()=>{game.maxZoneId=8;updateStaticUI();});
    await expect(card).toContainText('새 시련 도전 가능');
    await expect(card).toHaveClass(/has-new-challenge/);
    expect(await card.evaluate(el=>getComputedStyle(el,'::before').animationName)).toBe('atlas-border-travel');
    await page.locator('#atlas').click();
    const parent=frame.getByRole('button',{name:'탐험',exact:true});
    await expect(parent).toHaveClass(/has-new-challenge/);
    await parent.click();
    await page.emulateMedia({reducedMotion:'reduce'});
    expect(await card.evaluate(el=>getComputedStyle(el,'::before').display)).toBe('none');
    await card.screenshot({path:info.outputPath('new-trial-cue.png')});
    await child.evaluate(()=>{game.pendingLoopReady=true;updateStaticUI();});
    await expect(card).not.toHaveClass(/has-new-challenge/);
    await child.evaluate(()=>{game.pendingLoopReady=false;game.completedTrials.push('trial_2');updateStaticUI();});
    await expect(card).not.toHaveClass(/has-new-challenge/);
    await child.evaluate(()=>{game.unlockedTrials=['trial_3'];game.currencies.trialKey3=0;updateStaticUI();});
    await expect(card).toHaveClass(/has-new-challenge/);
    await card.click();
    await expect(frame.locator('#map-explore-trials')).toBeVisible();
    await expect(frame.locator('#ui-trial-list [data-trial-id]').first()).toHaveAttribute('data-trial-id','trial_3');
    await child.waitForFunction(() => !document.getElementById('tab-map').getAnimations({subtree:true}).some(animation => animation.playState === 'running'));
    await frame.locator('#ui-trial-list [data-trial-id]').first().screenshot({path:info.outputPath('trial-choices-dark.png')});
    await frame.locator('[data-trial-id="trial_3"]').getByRole('button',{name:'도전',exact:true}).click();
    expect(await child.evaluate(()=>({zone:game.currentZoneId,keys:game.currencies.trialKey3})))
        .toEqual({zone:'trial_3',keys:0});
    await page.locator('#atlas').click();
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    await expect(card).not.toHaveClass(/has-new-challenge/);
    await child.evaluate(()=>{game.currentZoneId=0;game.combatHalted=true;game.completedTrials.push('trial_3');updateStaticUI();});
    await expect(card).not.toHaveClass(/has-new-challenge/);
});

test('exploration shortcuts preserve combat and locked travel while showing tracked loot',async({page},info)=>{
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto('/tests/fixtures/world-tree-journey/index.html?review=regions');
    await expect(page.locator('#status')).toContainText('실제 전투');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    const atlas=frame.locator('#ui-exploration-atlas');
    const target=await child.evaluate(()=>{
        const entry=UNIQUE_DB.find(row=>row.dropOnly?.type==='beehive'&&!row.realmCodexOnly);
        uniqueHuntRuntime.toggle(uniqueHuntRuntime.getKey(entry));
        game.currentZoneId=0;game.maxZoneId=9;game.pendingLoopReady=true;game.combatHalted=true;
        updateStaticUI();return entry.name;
    });
    await expect(atlas.locator('.atlas-hunt-now')).toBeDisabled();
    const blocked=await child.evaluate(()=>{
        const before=JSON.stringify(game.currencies);
        [-1,0.5,100,'0',9].forEach(id=>explorationAtlasUi.hunt(id));
        return {zone:game.currentZoneId,same:before===JSON.stringify(game.currencies)};
    });
    expect(blocked).toEqual({zone:0,same:true});
    await child.evaluate(()=>{game.pendingLoopReady=false;updateStaticUI();});
    await atlas.locator('.atlas-hunt-now').click();
    expect(await child.evaluate(()=>game.currentZoneId)).toBe(9);
    expect(await child.evaluate(()=>{
        const before=JSON.stringify([game.runProgress,game.killsInZone,game.moveTimer]);
        explorationAtlasUi.hunt(9);
        return before===JSON.stringify([game.runProgress,game.killsInZone,game.moveTimer]);
    })).toBe(true);
    await page.locator('#atlas').click();
    const pip=frame.locator('#mobile-battle-pip');
    if(await pip.isVisible())await expect(atlas.locator('[data-atlas-current]')).not.toBeVisible();
    await child.evaluate(()=>{game.settings.showMobileBattlePip=false;updateMobileBattlePipVisibility();});
    await expect(atlas.locator('[data-atlas-current]')).toBeVisible();
    // Dispatch the real button synchronously to distinguish UI navigation from timer-driven combat.
    const unchanged=await child.evaluate(()=>{
        const snapshot=()=>JSON.stringify([game.currentZoneId,game.runProgress,game.killsInZone,game.currencies,game.enemies.map(enemy=>enemy.hp)]);
        const before=snapshot();document.querySelector('[data-atlas-current]').click();return before===snapshot();
    });
    expect(unchanged).toBe(true);
    await page.locator('#atlas').click();
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    const hive=atlas.locator('[data-atlas-route="map-explore-beehive"]');
    await expect(hive).toContainText(target);
    await expect(hive.locator('.atlas-activity-kind')).toHaveCount(0);
    await expect(atlas.locator('[data-atlas-route="map-explore-colony"] .atlas-activity-kind')).toHaveCount(0);
    await expect(atlas.locator('.atlas-activity-detail')).toHaveCount(0);
    await expect(atlas).not.toContainText('노릴 보상');
    await expect(atlas.locator('.atlas-route-reward')).toHaveCount(0);
    const reward=hive.getByRole('button',{name:'고유 장비',exact:true});
    await reward.click();
    await expect(frame.locator('#info-tooltip')).toBeVisible();
    await expect(frame.locator('#info-tooltip')).toContainText('고유 효과');
    await expect(hive).toBeVisible();
    await reward.focus();
    await reward.press('Enter');
    await expect(hive).toBeVisible();
    await expect(atlas.locator('h3')).toHaveCount(0);
    await expect(hive.locator('.atlas-route-status')).toHaveText(/벌집 열쇠 \d+개/);
    for (const action of await atlas.locator('.atlas-route-action').all()) await expect(action).toHaveText('이동');
    await expect(atlas.locator('[data-atlas-route="map-explore-root-boss"] .atlas-route-status')).toHaveCount(0);
    expect(await hive.locator('strong').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThan(18);
    await hive.focus();
    await child.evaluate(()=>{game.currencies.hiveKey++;updateStaticUI();});
    await expect(hive).toBeFocused();
    await atlas.screenshot({path:info.outputPath('exploration-shortcuts.png')});
    expect(await atlas.evaluate(element=>element.scrollWidth>element.clientWidth+1)).toBe(false);
    expect(errors).toEqual([]);
});

test('boss selection retains progress and ticket gates after removing the overview objective',async({page},info)=>{
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto('/tests/fixtures/world-tree-journey/index.html?review=regions');
    await expect(page.locator('#status')).toContainText('실제 전투');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    const names=await child.evaluate(()=>[getZone('pinnacle_underking').name,getZone('cosmos_astra').name]);
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    const titleStyle=await frame.locator('.atlas-region-hero h2').evaluate(el=>[getComputedStyle(el).fontSize,getComputedStyle(el).fontWeight,getComputedStyle(el).lineHeight]);
    await frame.locator('[data-atlas-route="map-explore-root-boss"]').click();
    expect(await child.evaluate(()=>document.getElementById('mobile-map-destination').value)).toBe('btn-map-explore-root-boss');
    expect(await frame.locator('#exploration-region-banner h2').evaluate(el=>[getComputedStyle(el).fontSize,getComputedStyle(el).fontWeight,getComputedStyle(el).lineHeight])).toEqual(titleStyle);
    const list=frame.locator('#ui-season-boss-list');
    await list.locator('[data-map-zone-group="pinnacleBosses"] .map-zone-group-header').click();
    expect(await list.locator('.encounter-card').evaluateAll(cards=>cards.every(card=>card.scrollWidth<=card.clientWidth+1&&card.getBoundingClientRect().width>250))).toBe(true);
    const underking=list.locator('.map-item').filter({hasText:names[0]});
    await expect(underking).toContainText('지하계 29/30층');
    await expect(underking.getByRole('button')).toBeDisabled();
    await child.evaluate(()=>{game.underworldProgress.highestFloor=31;updateStaticUI();});
    await expect(underking.getByRole('button',{name:'도전',exact:true})).toBeEnabled();
    await expect(list.locator('[data-map-zone-group="availableBosses"]')).toContainText(names[0]);
    expect(await list.locator('.map-zone-group').first().getAttribute('data-map-zone-group')).toBe('availableBosses');
    const underkingAction=underking.getByRole('button',{name:'도전',exact:true});
    await underkingAction.focus();
    await child.evaluate(()=>{game.clearedRootBosses.push('pinnacle_underking');updateStaticUI();});
    await expect(underking).toContainText('격파 완료');
    await expect(underkingAction).toBeFocused();
    await child.evaluate(()=>{game.pendingLoopReady=true;updateStaticUI();});
    await expect(list.locator('[data-map-zone-group="availableBosses"]')).toHaveCount(0);
    await expect(underking.getByRole('button')).toBeDisabled();
    await child.evaluate(()=>{game.pendingLoopReady=false;updateStaticUI();});
    const cosmos=list.locator('.map-item').filter({hasText:names[1]});
    await child.evaluate(()=>{
        game.cosmosAtlas.bossClears=['planet-45','planet-46','planet-47','planet-48','planet-49'];
        game.currencies.cosmosSovereignKey=0;updateStaticUI();
    });
    await expect(cosmos.getByRole('button',{name:'도전',exact:true})).toHaveCount(0);
    await child.evaluate(()=>{game.currencies.cosmosSovereignKey=1;updateStaticUI();});
    const ids=await list.locator('[data-boss-id]').evaluateAll(cards=>cards.map(card=>card.dataset.bossId));
    expect(new Set(ids).size).toBe(ids.length);
    await list.screenshot({path:info.outputPath('available-bosses.png')});
    const previousZone=await child.evaluate(()=>game.currentZoneId);
    await cosmos.locator('.encounter-heading').click();
    expect(await child.evaluate(()=>({zone:game.currentZoneId,keys:game.currencies.cosmosSovereignKey})))
        .toEqual({zone:previousZone,keys:1});
    await cosmos.getByRole('button',{name:'도전',exact:true}).click();
    expect(await child.evaluate(()=>({zone:game.currentZoneId,keys:game.currencies.cosmosSovereignKey})))
        .toEqual({zone:'cosmos_astra',keys:0});
    await page.locator('#atlas').click();
    await frame.getByRole('button',{name:'탐험',exact:true}).click();
    await frame.locator('[data-atlas-route="map-explore-root-boss"]').click();
    await expect(cosmos.getByRole('button',{name:'전투로 돌아가기',exact:true})).toBeVisible();
    expect(await child.evaluate(()=>{
        const snapshot=()=>JSON.stringify([game.currentZoneId,game.currencies,game.runProgress,game.enemies.map(enemy=>enemy.hp)]);
        const before=snapshot();document.querySelector('[data-boss-id="cosmos_astra"] .encounter-footer button').click();
        return before===snapshot();
    })).toBe(true);
    expect(errors).toEqual([]);
});

test('regional exploration separates landscapes and retains first-journey gates',async({page},info)=>{
    const errors=[];page.on('pageerror',error=>errors.push(error.message));
    await page.goto('/tests/fixtures/world-tree-journey/index.html');
    await page.getByRole('button',{name:'첫 여정',exact:true}).click();
    await expect(page.locator('#status')).toContainText('루프 1');
    const frame=page.frameLocator('#game');
    const child=page.frames().find(entry=>entry.parentFrame());
    await expect(frame.locator('#map-explore-hunting')).not.toBeVisible();
    expect(await child.evaluate(()=>game.mapExploreSubtab)).toBe('map-explore-hunting');
    // Project the existing first discovered map milestone; do not unlock any later content.
    await child.evaluate(()=>{game.maxZoneId=1;contentProgression.sync();updateStaticUI();});
    await frame.locator('#btn-tab-map').click();
    await expect(frame.locator('#map-explore-hunting')).toBeVisible();
    await expect(frame.locator('#ui-exploration-atlas')).not.toBeVisible();
    expect(await frame.locator('.map-item--act .map-item-main').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(16);
    await expect(frame.locator('#exploration-region-banner')).toContainText('액트');
    await frame.getByRole('button',{name:'전체 탐험',exact:true}).click();
    const atlas=frame.locator('#ui-exploration-atlas');
    await expect(atlas.locator('.atlas-region')).toHaveCount(0);
    await expect(atlas.getByRole('button',{name:'우주계',exact:true})).toHaveCount(0);
    await atlas.getByRole('button',{name:'나무',exact:true}).click();
    await expect(frame.locator('#map-explore-hunting')).toBeVisible();

    await page.getByRole('button',{name:'후반 권역',exact:true}).click();
    await expect(atlas.locator('.atlas-region')).toHaveCount(6);
    const pictures=atlas.locator('.atlas-region img');
    for(const picture of await pictures.all())await picture.scrollIntoViewIfNeeded();
    await expect.poll(()=>pictures.evaluateAll(images=>images.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);
    await atlas.locator('.atlas-heading').scrollIntoViewIfNeeded();
    expect(new Set(await pictures.evaluateAll(images=>images.map(img=>img.src))).size).toBe(6);
    const overflow=await atlas.evaluate(element=>element.scrollWidth>element.clientWidth+1);
    expect(overflow).toBe(false);
    await page.screenshot({path:info.outputPath('regional-overview.png')});
    await expect(atlas.getByRole('region',{name:'최종 탐험 목표'})).toHaveCount(0);
    const hunting=atlas.locator('[data-atlas-route="map-explore-hunting"]');
    await expect(hunting).toContainText('합일의 차륜');
    await expect(hunting.locator('.atlas-act-steps>span')).toHaveCount(10);
    expect(new Set(await hunting.locator('.atlas-act-steps>span').evaluateAll(steps=>steps.map(step=>Math.round(step.getBoundingClientRect().top)))).size).toBe(1);
    const hive=atlas.locator('[data-atlas-route="map-explore-beehive"]');
    await child.evaluate(()=>{game.currencies.hiveKey=0;game.claimableActRewards=[0];updateStaticUI();});
    await expect(hunting).toContainText('받을 보상 1');
    await hunting.getByRole('button',{name:'받을 보상 1',exact:true}).click();
    await expect(frame.locator('#reward-overlay')).toBeVisible();
    await expect(frame.locator('#reward-title')).toContainText('액트 1');
    expect(await frame.locator('#reward-overlay .tutorial-card').evaluate(el=>el.scrollWidth<=el.clientWidth+1&&el.getBoundingClientRect().height<=innerHeight)).toBe(true);
    await frame.locator('#reward-overlay').screenshot({path:info.outputPath('act-clear-reward.png')});
    await frame.locator('#reward-overlay').getByRole('button',{name:'나중에',exact:true}).click();
    await expect(hunting.getByRole('button',{name:'받을 보상 1',exact:true})).toBeVisible();
    await hunting.getByRole('button',{name:'받을 보상 1',exact:true}).click();
    await frame.locator('#reward-grid .reward-choice').first().click();
    await expect(frame.locator('#reward-overlay')).not.toBeVisible();
    expect(await child.evaluate(()=>game.claimedActRewards.includes(0)&&!game.claimableActRewards.includes(0))).toBe(true);
    await atlas.getByRole('button',{name:'탐험',exact:true}).click();
    await expect(hive).toContainText('벌집 열쇠 0개');
    await child.evaluate(()=>{game.currencies.hiveKey=2;updateStaticUI();});
    await expect(hive).toContainText('벌집 열쇠 2개');
    await atlas.screenshot({path:info.outputPath('tree-destinations.png')});
    await hive.click();
    await expect(frame.locator('#map-explore-beehive')).toBeVisible();
    expect(await child.evaluate(()=>game.currencies.hiveKey)).toBe(2);
    await frame.getByRole('button',{name:'전체 탐험',exact:true}).click();
    await atlas.getByRole('button',{name:'혼돈의 뿌리',exact:true}).click();
    await expect(atlas.locator('[data-atlas-route="map-explore-chaos"] .atlas-activity-kind')).toHaveText('루프 등반');
    await expect(atlas.locator('[data-atlas-route="map-tab-chaos-realm"] .atlas-activity-kind')).toHaveText('영구 등반');
    expect(await atlas.evaluate(el=>el.scrollWidth>el.clientWidth+1)).toBe(false);
    await atlas.getByRole('button',{name:'전체 탐험',exact:true}).click();
    await atlas.getByRole('button',{name:'창공',exact:true}).click();
    await expect(atlas.locator('.atlas-region-hero')).toContainText('최고 0층');
    await expect(atlas.locator('.atlas-region-hero')).not.toContainText('현재 루프');
    await expect(atlas.locator('.atlas-regions')).toHaveCount(0);
    await expect(atlas.getByRole('region',{name:'창공의 주변 콘텐츠'})).toContainText('운석');
    await atlas.locator('[data-atlas-route="map-tab-sky"]').click();
    await expect(frame.locator('#map-tab-sky')).toBeVisible();
    await expect(frame.locator('#exploration-region-banner')).toContainText('창공');
    const sky=await frame.locator('#exploration-region-banner img').getAttribute('src');
    await frame.getByRole('button',{name:'전체 탐험',exact:true}).click();
    await atlas.getByRole('button',{name:'지하계',exact:true}).click();
    await expect(frame.locator('#map-tab-underworld')).toBeVisible();
    await expect(frame.locator('#exploration-region-banner')).toContainText('최고 29층');
    await expect(frame.locator('#exploration-region-banner')).not.toContainText('현재 루프');
    await child.evaluate(()=>{game.loopProgressCurrent.bestUnderworldFloor=12;updateStaticUI();});
    await expect(frame.locator('#exploration-region-banner')).toContainText('최고 29층 / 현재 루프 12층');
    expect(await frame.locator('#exploration-region-banner img').getAttribute('src')).not.toBe(sky);
    await page.screenshot({path:info.outputPath('underworld-region.png')});
    await child.evaluate(()=>updateStaticUI());
    await expect(frame.locator('#map-tab-underworld')).toBeVisible();
    expect(errors).toEqual([]);
});
