const {test,expect}=require('@playwright/test');
test('growth inventory connects placement and crafting without duplicate mobile trays',async({page},info)=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('https://**',r=>r.fulfill({status:204,body:''}));await page.goto('/');
    await page.locator('#btn-startup-guest').click();await page.locator('[data-class-id="warrior"]').click();
    await page.waitForFunction(()=>battleAssets.ready&&!uiRefreshRunning&&!uiRefreshQueued);
    const fixture=await page.evaluate(()=>{
        clearInterval(gameTickHandle);gameTickHandle=null;game.season=30;contentProgression.sync();
        game.contentProgression.inherited=CONTENT_UNLOCK_CATALOG.map(row=>row.id);contentProgression.sync();
        syncGrowthBoardUnlocks({silent:true});
        const base=GROWTH_BASE_DB.find(row=>row.category==='flower');
        game.growthInventory=Array.from({length:40},(_,i)=>({...createGrowthItemFromBase(base,'normal',12),name:'검증 꽃 '+i}));
        game.currencies.growthEssence=20;game.currencies.magicBud=5;openTabPane('tab-growthboard');updateStaticUI();
        const id=game.growthInventory[0].id;
        for(let y=0;y<GROWTH_BOARD_H;y++)for(let x=0;x<GROWTH_BOARD_W;x++)if(planGrowthPlacement(id,x,y,0).ok)return{id,x,y};
        throw new Error('No legal placement');
    });
    await page.waitForFunction(()=>{if(uiRefreshRunning||uiRefreshQueued)return false;tutorialQueue.length=0;if(activeTutorial)dismissTutorial(false);return true;});
    const card=page.locator('#ui-growth-inventory .growth-item-card').first();
    if(info.project.use.isMobile){
        await expect(page.locator('.growth-tray-card')).toHaveCount(0);
        await page.getByRole('button',{name:'보관함에서 선택',exact:true}).click();
        await expect(page.locator('#growth-library')).toBeVisible();await card.scrollIntoViewIfNeeded();
        const box=await card.boundingBox(), cdp=await page.context().newCDPSession(page);
        const x=box.x+box.width/2,y=box.y+20;
        await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
        await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-100}]});
        await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();
        expect(await page.evaluate(()=>Object.keys(getActiveGrowthLoadout().placements).length)).toBe(0);
        expect(await page.evaluate(()=>growthSelection.itemId)).toBe(null);
    }else await expect(page.locator('.growth-tray-card')).toHaveCount(40);
    await card.getByRole('button',{name:'배치',exact:true}).click();
    await expect(page.locator('.growth-selection-label')).toContainText('검증 꽃 0');
    await page.locator(`#ui-growth-board [data-x="${fixture.x}"][data-y="${fixture.y}"]`).click();
    expect(await page.evaluate(id=>!!getActiveGrowthLoadout().placements[id],fixture.id)).toBe(true);
    if(info.project.use.isMobile)await page.getByRole('tab',{name:'보관함',exact:true}).click();
    await card.locator('.growth-item-head').click();
    await expect(page.locator('#ui-growth-craft-bench')).toBeVisible();
    await page.getByRole('button',{name:'마법 부여/재련 · 정수 1',exact:true}).click();
    await expect.poll(()=>page.evaluate(id=>findGrowthItemById(id).rarity,fixture.id)).toBe('magic');
    expect(await page.evaluate(()=>game.currencies.growthEssence)).toBe(19);
    const repeat=page.locator('#growth-workshop [data-repeat-craft="magicBud"]');
    await expect(repeat).toContainText('생장 정수 1개로 다시 제작');await repeat.click();
    await expect.poll(()=>page.evaluate(()=>game.currencies.growthEssence)).toBe(18);
    expect(await page.evaluate(()=>game.currencies.magicBud)).toBe(5);
    await page.evaluate(()=>{game.currencies.growthEssence=0;updateStaticUI();});await expect(repeat).toBeDisabled();
    expect(await page.evaluate(()=>game.growthInventory.length)).toBe(40);
    if(info.project.use.isMobile)await expect(page.getByRole('tab',{name:'제작대',exact:true})).toHaveAttribute('aria-selected','true');
    expect(errors).toEqual([]);
});
