const { test, expect } = require('@playwright/test');

for (const theme of ['dark', 'light']) test(`loop settlement shows real progress and preserves preparation and deferral in ${theme}`, async ({ page }, testInfo) => {
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('https://**', route => route.fulfill({ status: 204, body: '' }));
    await page.goto('/');
    await page.locator('#btn-startup-guest').click();
    await page.locator('#loop-hero-select-overlay [data-class-id="warrior"]').click();
    await page.waitForFunction(() => battleAssets.ready && !uiRefreshRunning && !uiRefreshQueued);
    await page.evaluate(theme => applyThemeMode(theme), theme);
    await page.evaluate(() => {
        clearInterval(gameTickHandle); gameTickHandle = null;
        tutorialQueue.length = 0; if (activeTutorial) dismissTutorial(false);
        game.unlocks.items = true; game.level = 63; game.loopKills = 456;
        ensureRecordsState(); game.records.currentLoop.activeMs = 3600000;
        handleSeasonLoopConditionMet();
    });
    const ready = page.locator('#loop-ready-overlay');
    await expect(ready).toBeVisible();
    await expect(ready).toContainText('루프 1 달성');
    await expect(ready).toContainText('1시간 0분');
    await expect(ready).toContainText('해금 포인트 +2');
    await expect(ready.getByText('나중에 루프', { exact: true })).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('loop-earned.png'), animations: 'disabled' });
    await ready.getByRole('button', { name: '장비 정리', exact: true }).click();
    await expect(ready).not.toBeVisible();
    await page.evaluate(() => updateStaticUI());
    await expect(ready).not.toBeVisible();
    expect(await page.evaluate(() => [game.season, game.pendingLoopReady, game.seasonPoints])).toEqual([1, true, 0]);
    await page.evaluate(() => switchTab('tab-battle'));
    const closeWindows = page.locator('#btn-close-all-windows');
    if (await closeWindows.isVisible()) await closeWindows.click();
    const reopen = page.locator('#loop-ready-banner button');
    await expect(reopen).toHaveCSS('pointer-events', 'auto');
    await reopen.click();
    await expect(ready).toBeVisible();
    await ready.getByRole('button', { name: '다음 루프 진행' }).click();
    await page.locator('#game-dialog-cancel').click();
    await expect(ready).toBeVisible();
    expect(await page.evaluate(() => game.season)).toBe(1);
    await ready.getByRole('button', { name: '다음 루프 진행' }).click();
    await page.locator('#game-dialog-confirm').click();
    await expect.poll(() => page.evaluate(() => game.season)).toBe(2);
    expect(await page.evaluate(() => game.seasonPoints)).toBe(1);
    expect(await page.evaluate(() => contentProgression.balance())).toBe(2);
    await expect(ready).not.toBeVisible();
    await expect(page.locator('#loop-hero-select-overlay')).toBeVisible();
    await page.locator('#loop-hero-select-overlay [data-class-id="warrior"]').click();
    await page.waitForFunction(() => !uiRefreshRunning && !uiRefreshQueued);
    await page.evaluate(() => {
        tutorialQueue.length = 0; if (activeTutorial) dismissTutorial(false);
        game.season = 10; game.abyssEndlessDepth = 20;
        game.loopProgressCurrent.chaos20Cleared = true; game.loopProgressCurrent.bestAbyssDepth = 20;
        handleSeasonLoopConditionMet();
    });
    const decision = page.locator('#loop-decision-overlay');
    await expect(decision).toBeVisible();
    await expect(decision).toContainText('다음 콘텐츠를 직접 선택');
    await page.screenshot({ path: testInfo.outputPath('loop-defer.png'), animations: 'disabled' });
    await decision.getByRole('button', { name: '나중에 루프' }).click();
    await expect(decision).not.toBeVisible();
    expect(await page.evaluate(() => [game.season, game.abyssEndlessDepth, game.pendingLoopDecision])).toEqual([10, 21, false]);
    expect(errors).toEqual([]);
});
