const { test, expect } = require('@playwright/test');

test('mobile full menu contains keyboard focus and preserves it across refreshes', async ({ page }, info) => {
    test.skip(!info.project.use.isMobile, 'Mobile full menu');
    await page.route('https://**', route => route.fulfill({ status: 204, body: '' }));
    await page.goto('/');
    await page.locator('#btn-startup-guest').tap();
    await page.locator('[data-class-id="warrior"]').tap();
    await page.waitForFunction(() => battleAssets.ready && !uiRefreshRunning && !uiRefreshQueued);
    await page.evaluate(() => {
        clearInterval(gameTickHandle); gameTickHandle = null; game.season = 100; game.level = 100;
        game.contentProgression.inherited = CONTENT_UNLOCK_CATALOG.map(row => row.id); contentProgression.sync();
        updateTabUnlockButtons(); applyTabHeaderOrder();
        tutorialQueue.length = 0; if (activeTutorial) dismissTutorial(false);
    });
    const menu = page.locator('#tab-header-main');
    const more = page.locator('#btn-mobile-nav-more');
    const close = menu.getByRole('button', { name: '전체 메뉴 닫기' });
    await more.tap();
    await expect(close).toBeFocused();
    await menu.locator('#btn-tab-character').focus();
    await page.evaluate(() => applyTabHeaderOrder());
    await expect(menu.locator('#btn-tab-character')).toBeFocused();
    await expect(menu).toHaveAttribute('aria-hidden', 'false');
    await close.focus();
    await page.keyboard.press('Shift+Tab');
    expect(await menu.evaluate(el => el.contains(document.activeElement))).toBe(true);
    await page.keyboard.press('Tab');
    await expect(close).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(menu).toBeHidden();
    await expect(more).toBeFocused();
    await more.press('Enter');
    await expect(close).toBeFocused();
    await menu.locator('#btn-tab-character').focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('#tab-character')).toBeVisible();
    await expect(menu).toBeHidden();
    await more.click();
    await page.keyboard.press('Escape');
    await expect(page.locator('#tab-character')).toBeVisible();
    await page.locator('#btn-tab-battle').focus();
    await page.keyboard.press('Space');
    await expect(page.locator('#tab-character')).toBeHidden();
    await more.click();
    await page.evaluate(() => { requestGameConfirmation('메뉴 위 확인 창'); });
    await expect(page.locator('#game-dialog-overlay')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.locator('#game-dialog-overlay')).toBeHidden();
    await expect(menu).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(more).toBeFocused();
    await page.setViewportSize({ width: 1440, height: 900 });
    await expect(page.locator('#btn-tab-character')).not.toHaveAttribute('data-mobile-tab-button');
});
