const {test,expect}=require('@playwright/test');
test('mobile currency inventory explains blocked choices and spends only on use',async({page},info)=>{
    test.skip(!info.project.use.isMobile,'Mobile crafting inventory');
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('https://**',r=>r.fulfill({status:204,body:''}));
    await page.goto('/');await page.locator('#btn-startup-guest').tap();await page.locator('[data-class-id="warrior"]').tap();
    await page.waitForFunction(()=>battleAssets.ready&&!uiRefreshRunning&&!uiRefreshQueued);
    await page.evaluate(()=>{
        clearInterval(gameTickHandle);gameTickHandle=null;game.season=100;
        game.contentProgression.inherited=CONTENT_UNLOCK_CATALOG.map(r=>r.id);contentProgression.sync();
        for(const key of Object.keys(ORB_DB))game.currencies[key]=0;
        game.currencies.magicBud=2;game.currencies.sapBud=2;
        game.inventory=[createItemFromBase(BASE_ITEM_DB.find(b=>b.id==='war_helm'),'normal',1)];
        openTabPane('tab-items');switchItemSubtab('item-tab-craft');selectForCrafting(game.inventory[0].id,false);updateStaticUI();
    });
    await settle(page);
    await page.getByRole('button',{name:'기타 재화',exact:true}).tap();
    const overlay=page.locator('.cl-catalog');
    await overlay.locator('[data-resource="sapBud"]').tap();
    await expect(overlay.locator('[data-apply]')).toBeDisabled();
    await overlay.locator('[data-resource="magicBud"]').tap();
    await expect(overlay.locator('.cl-resource-detail')).toContainText('일반 아이템을 매직');
    await overlay.locator('[data-apply]').tap();
    expect(await page.evaluate(()=>game.currencies.magicBud)).toBe(2);
    await page.locator('[data-command="craft"]').tap();
    await expect.poll(()=>page.evaluate(()=>game.inventory[0].rarity)).toBe('magic');
    expect(await page.evaluate(()=>game.currencies.magicBud)).toBe(1);
    expect(await page.evaluate(()=>game.currencies.sapBud)).toBe(2);
    await page.evaluate(()=>{for(const key of Object.keys(ORB_DB))game.currencies[key]=0;updateStaticUI();});
    await settle(page);
    await page.getByRole('button',{name:'기타 재화',exact:true}).tap();
    await expect(overlay.locator('.cl-resource-empty')).toBeVisible();
    await overlay.locator('[data-close]').tap();
    await page.evaluate(()=>{for(const key of Object.keys(ORB_DB))game.currencies[key]=20;updateStaticUI();});
    await settle(page);
    await page.getByRole('button',{name:'기타 재화',exact:true}).tap();
    await overlay.locator('.cl-resource-list').evaluate(el=>{el.scrollTop=el.scrollHeight;});
    await expect(overlay.locator('[data-close]')).toBeInViewport();
    await overlay.locator('[data-close]').tap();
    expect(errors).toEqual([]);
});
async function settle(page){await page.waitForFunction(()=>{if(uiRefreshRunning||uiRefreshQueued)return false;tutorialQueue.length=0;if(activeTutorial)dismissTutorial(false);return true;});}
