const {test,expect}=require('@playwright/test');
test('workshop preserves unseal choices, complete unique descriptions and current exchange funds',async({page},info)=>{
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('https://**',r=>r.fulfill({status:204,body:''}));
    await page.goto('/');await page.locator('#btn-startup-guest').click();await page.locator('[data-class-id="warrior"]').click();
    await page.waitForFunction(()=>battleAssets.ready&&!uiRefreshRunning&&!uiRefreshQueued);
    await page.evaluate(()=>{
        clearInterval(gameTickHandle);gameTickHandle=null;game.season=20;contentProgression.sync();
        game.contentProgression.inherited.push('talisman');contentProgression.sync();game.talismanInventory=[];
        Object.assign(game.currencies,{sealShard:80,strongSealShard:2,radiantSealShard:7});
        openTabPane('tab-talisman');updateStaticUI();
    });
    await page.waitForFunction(()=>{if(uiRefreshRunning||uiRefreshQueued)return false;tutorialQueue.length=0;if(activeTutorial)dismissTutorial(false);return true;});
    const selector=page.locator('#talisman-unseal-source');
    if(info.project.use.isMobile){
        await page.getByRole('tab',{name:'공방',exact:true}).click();await selector.selectOption('strongSealShard');
        await expect(page.locator('.talisman-unseal-source')).toHaveCount(1);
    }else await expect(page.locator('.talisman-unseal-source')).toHaveCount(3);
    const compare=()=>page.locator('[data-unseal-source="strongSealShard"]').getByRole('button',{name:/후보 비교/});
    await compare().click();
    await expect.poll(()=>page.evaluate(()=>game.currencies.strongSealShard)).toBe(1);
    await page.evaluate(()=>{game.talismanUnseal.current={id:7001,name:'고유 후보',isUnique:true,rarity:'고유',shape:'DASH2',cells:[{x:0,y:0},{x:1,y:0}],stats:[{stat:'crit',label:'치명타 확률',value:3},{stat:'flatHp',label:'최대 생명력',value:20}]};updateStaticUI();});
    const candidate=page.locator('.talisman-unseal-candidate');
    await expect(candidate).toContainText('치명타 확률');await expect(candidate).toContainText('최대 생명력');
    await expect(candidate).not.toContainText('undefined');
    await candidate.getByRole('button',{name:'이 부적 선택',exact:true}).click();
    expect(await page.evaluate(()=>game.talismanInventory[0].id)).toBe(7001);
    await compare().click();
    await page.evaluate(()=>{game.talismanUnseal.rollsLeft=2;game.talismanUnseal.totalRolls=2;updateStaticUI();});
    await candidate.getByRole('button',{name:'다음 후보',exact:true}).click();
    await expect(candidate).toContainText('1/2');await expect(candidate.getByRole('button',{name:'다음 후보'})).toBeDisabled();
    await candidate.getByRole('button',{name:'이 부적 선택',exact:true}).click();
    if(info.project.use.isMobile)await selector.selectOption('radiantSealShard');
    await page.locator('[data-unseal-source="radiantSealShard"]').getByRole('button',{name:/바로 해제/}).click();
    await expect.poll(()=>page.evaluate(()=>game.talismanInventory.length)).toBe(9);
    expect(await page.evaluate(()=>game.currencies.radiantSealShard)).toBe(0);
    await page.locator('.talisman-shard-exchange > summary').click();
    const exchange=page.getByRole('button',{name:'편린 80 → 강력 편린 1',exact:true});
    await exchange.click();await page.locator('#game-dialog-cancel').click();
    expect(await page.evaluate(()=>game.currencies.sealShard)).toBe(80);
    await exchange.click();await page.evaluate(()=>{game.currencies.sealShard=160;});
    await page.locator('#game-dialog-confirm').click();
    await expect.poll(()=>page.evaluate(()=>game.currencies.sealShard)).toBe(80);
    expect(await page.evaluate(()=>game.currencies.strongSealShard)).toBe(1);
    await exchange.click();await page.evaluate(()=>{game.currencies.sealShard=79;});
    await page.locator('#game-dialog-confirm').click();
    expect(await page.evaluate(()=>game.currencies.sealShard)).toBe(79);
    expect(await page.evaluate(()=>game.currencies.strongSealShard)).toBe(1);
    await page.evaluate(()=>{game.talismanUnseal={current:rollTalismanCandidate('sealShard'),rollsLeft:1,totalRolls:1};updateStaticUI();});
    await candidate.getByRole('button',{name:'후보 파괴',exact:true}).click();
    await expect(page.locator('.talisman-unseal-source')).toHaveCount(info.project.use.isMobile?1:3);
    expect(errors).toEqual([]);
});
