// Import the old game's equipment affix table (MOD_DB in js/state.js) into src/data/affixes.ts.
// Only options the new combat model uses are kept; the rest wait for their systems (summons,
// spells, energy shield, gems). Run again when the old table changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (path: string) => fileURLToPath(new URL(path, import.meta.url));

interface OldMod {
  id: string; statId?: string; type: string; statName: string; slots: string[]; weight?: number;
  tierValues: [number, number][]; valueStep?: number;
  compound?: { statId: string; statName: string; tierValues: [number, number][]; valueStep?: number }[];
}

const lines = readFileSync(here('../../js/state.js'), 'utf8').split('\n');
const start = lines.findIndex(l => l.startsWith('const MOD_DB = ['));
const end = lines.findIndex((l, i) => i > start && l.startsWith('];'));
if (start < 0 || end < 0) throw new Error('MOD_DB not found in js/state.js');
const old = JSON.parse(`[${lines.slice(start + 1, end).join('\n').replace(/,\s*$/, '')}]`) as OldMod[];

const KINDS: Record<string, string> = { 무기: 'weapon', 방패: 'offhand', 투구: 'helmet', 갑옷: 'armor', 장갑: 'gloves', 신발: 'boots', 허리띠: 'belt', 목걸이: 'amulet', 반지: 'ring' };
/** Old stat id → new stat id; old per-slot flat damage variants all feed flat damage. */
const STAT: Record<string, string> = {
  flatDmg: 'flatDmg', ringFlatDmg: 'flatDmg', gloveFlatDmg: 'flatDmg', accessoryFlatDmg: 'flatDmg', weaponFlatDmgPct: 'weaponDmgPct',
  pctDmg: 'pctDmg', attackPctDmg: 'attackPctDmg', meleePctDmg: 'meleePctDmg', projectilePctDmg: 'projectilePctDmg',
  physPctDmg: 'physPctDmg', elementalPctDmg: 'elementalPctDmg', flatHp: 'flatHp', pctHp: 'pctHp', armor: 'armor', armorPct: 'armorPct',
  dr: 'dr', aspd: 'aspd', crit: 'crit', critDmg: 'critDmg', move: 'move', resF: 'resF', resC: 'resC', resL: 'resL', resAll: 'resAll',
  resChaos: 'resChaos', regen: 'regen', leech: 'leech', ds: 'ds', compoundArmor: 'armor', compoundWeaponDmg: 'flatDmg'
};
/** Options that only matter for one class's attack. */
const CLASSES: Record<string, string[]> = {
  meleePctDmg: ['warrior'], physPctDmg: ['warrior'], projectilePctDmg: ['arcanist'], elementalPctDmg: ['arcanist']
};

const kept = old.filter(m => STAT[m.id] && (!m.compound || m.compound.every(c => STAT[c.statId])));
const table = kept.map(m => ({
  id: m.id, type: m.type, name: m.statName, stat: STAT[m.id],
  kinds: m.slots.map(s => { if (!KINDS[s]) throw new Error(`${m.id}: unknown slot ${s}`); return KINDS[s]; }),
  weight: m.weight ?? 1, step: m.valueStep ?? 1, tiers: m.tierValues,
  ...(CLASSES[m.id] ? { classes: CLASSES[m.id] } : {}),
  ...(m.compound ? { extra: { stat: STAT[m.compound[0]!.statId], name: m.compound[0]!.statName, step: m.compound[0]!.valueStep ?? 0.01, tiers: m.compound[0]!.tierValues } } : {})
}));
for (const m of table) if (m.tiers.length !== 20) throw new Error(`${m.id}: expected 20 tiers, got ${m.tiers.length}`);

writeFileSync(here('../src/data/affixes.ts'), `// Generated by tools/import-affixes.ts from the old game's MOD_DB (js/state.js). Do not edit by hand.
// ${table.length} of ${old.length} options: the ones the new combat model uses.
import type { AffixDef } from './affix-types.ts';

export const AFFIXES: readonly AffixDef[] = ${JSON.stringify(table)};
`);
console.log(`affixes: kept ${table.length} of ${old.length}: ${table.map(m => m.id).join(', ')}`);
