// Convert the old game's authored act presets (data/act-exploration-maps.js, a classic browser
// script) into a typed module for the new core. Run again only when the old presets change.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { readAlpha, visibleBox } from './png.ts';

const here = (path: string) => fileURLToPath(new URL(path, import.meta.url));
const source = readFileSync(here('../../data/act-exploration-maps.js'), 'utf8');
// The old script ends by exposing its tables; a no-op stands in for that browser helper.
const context: Record<string, unknown> = { safeExposeData: () => {} };
vm.createContext(context);
vm.runInContext(`${source}\nthis.maps = ACT_EXPLORATION_MAPS; this.art = ACT_EXPLORATION_ART;`, context);
const maps = context.maps as unknown[];
if (!Array.isArray(maps) || maps.length !== 10) throw new Error(`expected 10 act presets, got ${String(maps?.length)}`);

const body = JSON.stringify(maps, null, 1).replace(/\n\s*/g, ' ');
writeFileSync(here('../src/data/act-maps.ts'), `// Generated by tools/import-acts.ts from the old game's data/act-exploration-maps.js. Do not edit by hand.
import type { ActPreset } from '../core/types.ts';

export const ACT_PRESETS: readonly ActPreset[] = ${body};
`);
const art = context.art as Record<string, { props: string; regions: [number, number, number, number][]; propBounds?: unknown }>;
if (!art || typeof art !== 'object' || !('root' in art)) throw new Error('expected ACT_EXPLORATION_ART with a root profile');
// Prop crop boxes are measured here once: browsers cannot read pixels of images opened from disk.
for (const profile of Object.values(art)) {
  const alpha = readAlpha(here(`../../${profile.props}`));
  profile.propBounds = profile.regions.map(region => visibleBox(alpha, region));
}
writeFileSync(here('../src/data/act-art.ts'), `// Generated by tools/import-acts.ts from the old game's ACT_EXPLORATION_ART. Do not edit by hand.
// Visual profiles only: materials (4 textures), prop atlas regions and how props are placed.
import type { ActArtProfile } from './act-art-profile.ts';

export const ACT_ART: Readonly<Record<string, ActArtProfile>> = ${JSON.stringify(art, null, 1).replace(/\n\s*/g, ' ')};
`);
console.log(`act presets: ${maps.length}, art profiles: ${Object.keys(art).join(', ')}`);
